[buildPlans.VENXMomo]
family = "VENXMomo"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.VENXMomo.variants]
  inherits = "ss14"

    [buildPlans.VENXMomo.variants.design]
    capital-b = "standard-interrupted-serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothed-serifless-hooked"
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-k = "straight-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "open-serifless"
    capital-q = "crossing-baseline"
    capital-r = "straight-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "double-storey-serifed"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-bottom-serifed"
    e = "rounded"
    f = "serifless"
    g = "single-storey-flat-hook-serifless"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "short-leg-serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "serifless"
    t = "flat-hook"
    u = "toothed-bottom-right-serifed"
    w = "straight-vertical-sides-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    zero = "tall-slashed-cutout"
    two = "straight-neck-serifless"
    four = "open-non-crossing-serifless"
    five = "upright-flat-serifless"
    six = "straight-bar"
    seven = "straight-serifless-crossbar"
    eight = "crossing-asymmetric"
    punctuation-dot = "square"
    tilde = "high"
    asterisk = "penta-mid"
    caret = "high"
    paren = "large-contour"
    brace = "straight"
    number-sign = "upright-tall"
    at = "fourfold-solid-inner-tall"
    dollar = "interrupted"
    cent = "bar-interrupted-cap"
    percent = "rings-segmented-slash"
    lig-ltgteq = "flat"
    lig-neq = "more-slanted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-plus-chain = "with-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

    [buildPlans.VENXMomo.variants.italic]
    capital-n = "asymmetric-serifless"
    capital-p = "open-serifless"
    capital-q = "crossing-baseline"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "double-storey-serifed"
    c = "serifless"
    m = "short-leg-serifless"
    n = "straight-serifless"
    u = "toothed-bottom-right-serifed"
    w = "straight-vertical-sides-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    zero = "tall-slashed-cutout"
    four = "open-non-crossing-serifless"
    seven = "straight-serifless-crossbar"
    eight = "crossing-asymmetric"
    punctuation-dot = "square"
    tilde = "high"
    asterisk = "penta-mid"
    brace = "straight"
    number-sign = "upright-tall"
    dollar = "interrupted"
    percent = "rings-segmented-slash"
    lig-ltgteq = "flat"

    [buildPlans.VENXMomo.variants.oblique]
    capital-b = "standard-interrupted-serifless"
    capital-f = "serifless"
    capital-g = "toothed-serifless-hooked"
    capital-j = "flat-hook-serifed"
    capital-n = "asymmetric-serifless"
    capital-p = "open-serifless"
    capital-q = "crossing-baseline"
    capital-r = "straight-open-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "straight-serifless-with-horizontal-crossbar"
    a = "double-storey-serifed"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-bottom-serifed"
    e = "rounded"
    f = "serifless"
    g = "single-storey-flat-hook-serifless"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "short-leg-serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    r = "serifless"
    t = "flat-hook"
    u = "toothed-bottom-right-serifed"
    w = "straight-vertical-sides-serifless"
    z = "straight-serifless-with-horizontal-crossbar"
    zero = "tall-slashed-cutout"
    two = "straight-neck-serifless"
    four = "open-non-crossing-serifless"
    five = "upright-flat-serifless"
    seven = "straight-serifless-crossbar"
    eight = "crossing-asymmetric"
    punctuation-dot = "square"
    tilde = "high"
    asterisk = "penta-mid"
    paren = "large-contour"
    brace = "straight"
    number-sign = "upright-tall"
    at = "fourfold-solid-inner-tall"
    dollar = "interrupted"
    cent = "bar-interrupted-cap"
    percent = "rings-segmented-slash"
    lig-ltgteq = "flat"
    lig-neq = "slightly-slanted"

[buildPlans.VENXMomo.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.VENXMomo.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.VENXMomo.widths.Normal]
shape = 600
menu = 5
css = "normal"
